//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxoCover {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AxoCover.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort Tests.
        /// </summary>
        public static string AbortTests {
            get {
                return ResourceManager.GetString("AbortTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Cover.
        /// </summary>
        public static string AutoCover {
            get {
                return ResourceManager.GetString("AutoCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building....
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating....
        /// </summary>
        public static string CalculatingOutputSize {
            get {
                return ResourceManager.GetString("CalculatingOutputSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage.
        /// </summary>
        public static string Coverage {
            get {
                return ResourceManager.GetString("Coverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing tests ({0} / {1})....
        /// </summary>
        public static string ExecutingTests {
            get {
                return ResourceManager.GetString("ExecutingTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating coverage report....
        /// </summary>
        public static string GeneratingCoverageReport {
            get {
                return ResourceManager.GetString("GeneratingCoverageReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing test runner....
        /// </summary>
        public static string InitializingTestRunner {
            get {
                return ResourceManager.GetString("InitializingTestRunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open and build a solution to start testing..
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directories.
        /// </summary>
        public static string OutputDirectories {
            get {
                return ResourceManager.GetString("OutputDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Tests.
        /// </summary>
        public static string RunTests {
            get {
                return ResourceManager.GetString("RunTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning solution for tests....
        /// </summary>
        public static string ScanningForTests {
            get {
                return ResourceManager.GetString("ScanningForTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string ShowCoverage {
            get {
                return ResourceManager.GetString("ShowCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at {0}.
        /// </summary>
        public static string StackItemFormat {
            get {
                return ResourceManager.GetString("StackItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test run aborted..
        /// </summary>
        public static string TestRunAborted {
            get {
                return ResourceManager.GetString("TestRunAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test run failed..
        /// </summary>
        public static string TestRunFailed {
            get {
                return ResourceManager.GetString("TestRunFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test runners.
        /// </summary>
        public static string TestRunners {
            get {
                return ResourceManager.GetString("TestRunners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search test methods, classes and projects.
        /// </summary>
        public static string TestSearchPlaceholder {
            get {
                return ResourceManager.GetString("TestSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test settings.
        /// </summary>
        public static string TestSettings {
            get {
                return ResourceManager.GetString("TestSettings", resourceCulture);
            }
        }
    }
}
